export const DangVienExcelMapping = [
  { header: "B", column: "gioiTinh", display: "Giới Tính" },
  { header: "C", column: "dangBoTinh", display: "Đảng bộ tỉnh" },
  { header: "D", column: "dangBoHuyen", display: "Đảng bộ huyện" },
  { header: "E", column: "soLyLich", display: "Số Lý lịch" },
  { header: "F", column: "soTheDangVien", display: "Số thẻ đảng viên" },
  { header: "G", column: "tenDangDung", display: "Tên đang dùng" },
  { header: "H", column: "tenKhaiSinh", display: "Tên khai sinh" },
  { header: "I", column: "noiSinh", display: "Nơi Sinh" },
  { header: "J", column: "ngaySinh", display: "Ngày sinh" },
  { header: "K", column: "queQuan", display: "Quê quán" },
  { header: "L", column: "thuongTru", display: "Thường trú" },
  { header: "M", column: "tamTru", display: "Tạm trú" },
  { header: "N", column: "danToc", display: "Dân tộc" },
  { header: "O", column: "tonGiao", display: "Tôn giáo" },
  { header: "P", column: "thanhPhanGiaDinh", display: "Thành phần gia đình" },
  { header: "Q", column: "ngheNghiep", display: "Nghề nghiệp" },
  { header: "R", column: "ngayVaoDang", display: "Ngày vào đảng" },
  { header: "S", column: "chiBoVaoDang", display: "Chi bộ vào đảng" },
  {
    header: "T",
    column: "ngayCapThamQuyenVaoDang",
    display: "Ngày cấp thẩm quyền vào đảng",
  },
  {
    header: "U",
    column: "ngayChinhThucVaoDang",
    display: "Ngày chính thức vào đảng",
  },
  {header: "V",column: "chiBoChinhThucVaoDang",display: "Chi Bộ chính thức vào đảng"},
  { header: "W", column: "ngayDuocTuyen", display: "Ngày được tuyển" },
  { header: "X", column: "coQuanTuyenDung", display: "Cơ quan tuyển dụng" },
  { header: "Y", column: "ngayVaoDoan", display: "Ngày vào đoàn" },
  {
    header: "Z",
    column: "thamGiaToChucXaHoi",
    display: "Tham gia tổ chức sự xã hội",
  },
  { header: "AA", column: "ngayNhapNgu", display: "Ngày nhập ngũ" },
  { header: "AB", column: "ngayXuatNgu", display: "Ngày xuất ngũ" },
  { header: "AC", column: "trinhDo", display: "Trình độ" },
  {
    header: "AD",
    column: "tinhTrangSucKhoe",
    display: "Tình trạng sức khỏe",
  },
  { header: "AE", column: "soCmnd", display: "Số CMND" },
  {
    header: "AF",
    column: "quaTrinhHoatDongVaCongTac",
    display: "Quá trình hoạt động và công tác",
  },
  { header: "AG", column: "daoTao", display: "Đào tạo" },
  { header: "AH", column: "khenThuong", display: "Khen thưởng" },
  { header: "AI", column: "huyHieu", display: "Huy Hiệu" },
  { header: "AJ", column: "danhHieu", display: "Danh Hiệu" },
  {
    header: "AK",
    column: "dacDiemLichSuBanThan",
    display: "Đặc điểm lịch sử bản thân",
  },
  { header: "AL", column: "quanHeNuocNgoai", display: "Quan hệ nước ngoài" },
  { header: "AM", column: "chiBoCoSo", display: "Chi bộ cơ sở" },
  { header: "AN", column: "chiBo", display: "Chi bộ" },
  { header: "AO", column: "boPhan", display: "Bộ phần" },
  { header: "AP", column: "mienCongTacNgay", display: "Miễn Công tác ngày" },
  {
    header: "AQ",
    column: "ngayKhoiPhucDang",
    display: "Ngày khôi phục đảng",
  },
  {
    header: "AR",
    column: "chiBoKhoiPhucDang",
    display: "Chi bộ khôi phục đảng",
  },
  {
    header: "AS",
    column: "biXuLyTheoPhapLuat",
    display: "Bị xử lý theo pháp luật",
  },
  {
    header: "AT",
    column: "lamViecTrongCheDoCu",
    display: "Làm việc trong chế độ cũ",
  },
  { header: "AU", column: "daDiNuocNgoai", display: "Đã đi nước ngoài" },
  {
    header: "AV",
    column: "thamGiaToChucNuocNgoai",
    display: "Tham gia tổ chức nước ngoài",
  },
  {
    header: "AW",
    column: "coNguoiThanNuocNgoai",
    display: "Có người thân ở nước ngoài",
  },
  { header: "AX", column: "tongThuNhap", display: "Tổng thu nhập" },
  { header: "AY", column: "binhQuan", display: "Bình quân" },
  { header: "AZ", column: "loaiNhaDuocCap", display: "Loại nhà được cấp" },
  {
    header: "BA",
    column: "dienTichNhaDuocCap",
    display: "Diện tích nhà dược cấp",
  },
  { header: "BB", column: "loaiNhaDuocMua", display: "Loại nhà được mua" },
  {
    header: "BC",
    column: "dienTichNhaDuocMua",
    display: "Diện tích nhà được mua",
  },
  { header: "BD", column: "datDuocCap", display: "Đất được cấp" },
  { header: "BE", column: "datDuocMua", display: "Đất được mua" },
  { header: "BF", column: "hoatDongKinhTe", display: "Hoạt động kinh tế" },
  {
    header: "BG",
    column: "dienTichDatTrangTrai",
    display: "Diện tích đất trang trại",
  },
  { header: "BH", column: "soLaoDongThue", display: "Sở lao động thuế" },
  { header: "BI", column: "taiSanCoGiaTri", display: "Tài sản có giá trị" },
  { header: "BJ", column: "giaTriTaiSan", display: "Giá trị tài sản" },
  {
    header: "BK",
    column: "ngayVaoDangLanHai",
    display: "Ngày vào đảng lần hai",
  },
  {
    header: "BL",
    column: "chiBoVaoDangLanHai",
    display: "Chi bộ vào đảng lần hai",
  },
  {
    header: "BM",
    column: "nguoiGioiThieuMot",
    display: "Người giới thiệu 1",
  },
  {
    header: "BN",
    column: "chucVuNguoiGioiThieuMot",
    display: "Chức vụ người giới thiệu 1",
  },
  {
    header: "BO",
    column: "nguoiGioiThieuHai",
    display: "Người giới thiệu 2",
  },
  {
    header: "BP",
    column: "chucVuNguoiGioiThieuHai",
    display: "Chức vụ người giới thiệu 2",
  },
  {
    header: "BQ",
    column: "ngayChinhThucVaoLanHai",
    display: "Ngày chính thức vào lần 2",
  },
  {
    header: "BR",
    column: "chiBoChinhThucVaoDangLanHai",
    display: "Chi bộ chính thức vào lần 2",
  },
  { header: "BS", column: "kyLuat", display: "Kỷ luật" },
  { header: "BT", column: "thoiGianBiXoa", display: "Thời gian bị xóa" },
  { header: "BU", column: "chiBoBiXoa", display: "Chi bộ bị xóa" },
  { header: "BV", column: "quanHeGiaDinh", display: "Quan hệ gia đình" },
  { header: "BW", column: "anh3x4", display: "Ảnh" },
  {
    header: "BX",
    column: "ngayQuyetDinhKetNap",
    display: "Ngày quyết định kết nạp",
  },
  { header: "BY", column: "giaoDucPhoThong", display: "Giáo dục phổ thông" },
  {
    header: "BZ",
    column: "giaoDucNgheNghiep",
    display: "Giáo dục nghề nghiệp",
  },
  {
    header: "CA",
    column: "giaoDucDaiHocVaSauDaiHoc",
    display: "Giáo dục đại học và sau đại học",
  },
  { header: "CB", column: "hocVi", display: "Học vị" },
  { header: "CC", column: "hocHam", display: "Học hàm" },
  { header: "CD", column: "lyLuanChinhTri", display: "Lý luân chính trị" },
  { header: "CE", column: "ngoaiNgu", display: "Ngoại ngữ" },
  { header: "CF", column: "tinHoc", display: "Tin Học" },
  { header: "CG", column: "canCuocCongDan", display: "Căn cước công dân" },
  {
    header: "CH",
    column: "nguoiGioiThieuMotLanHai",
    display: "Người giới thiệu 1 lần hai",
  },
  {
    header: "CI",
    column: "chucVuNguoiGioiThieuMotLanHai",
    display: "Chức vụ người giới thiệu 1 lần hai",
  },
  {
    header: "CJ",
    column: "nguoiGioiThieuHaiLanHai",
    display: "Người giới thiệu 2 lần hai",
  },
  {
    header: "CK",
    column: "chucVuNguoiGioiThieuHaiLanHai",
    display: "Chức vụ người giới thiệu 2 lần hai",
  },
  { header: "CL", column: "thuongBinhLoai", display: "Thương binh loại" },
  { header: "CM", column: "giaDinhLietSi", display: "Gia đình liệt sĩ" },
  {
    header: "CN",
    column: "giaDinhCoCongCachMang",
    display: "Gia đình có công cách mạng",
  },
  { header: "CO", column: "tinhTrangQuanLy", display: "Tình trạng quản lý" },
  { header: "CP", column: "trangThai", display: "Trạng thái" },
];
